name: Experimental workflow
on:
  pull_request:
    branches:
      - nightly
      - master
      - develop
      - verbose
    paths-ignore:
      - '**.md'
      - 'examples/**'
  push:
    branches:
      - nightly
      - master
      - develop
      - verbose
    paths-ignore:
      - '**.md'
      - 'examples/**'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, windows-latest, macos-latest]
        php-versions: ['8.0']
    env:
      extensions: xml, opcache, pcov
      key: cache-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cache environment
        id: cache-env
        uses: shivammathur/cache-extensions@develop
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-env.outputs.dir }}
          key: ${{ steps.cache-env.outputs.key }}
          restore-keys: ${{ steps.cache-env.outputs.key }}

      - name: Setup PHP with extensions and custom config
        run: node dist/index.js
        env:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.extensions }}
          ini-values: post_max_size=256M, short_open_tag=On, date.timezone=Asia/Kolkata
          coverage: pcov

      - name: Testing PHP version
        run: |
          php -v
          php -r "if(strpos(phpversion(), '${{ matrix.php-versions }}') === false) {throw new Exception('Wrong PHP version Installed');}"

      - name: Testing Composer version
        run: |
          composer -V
          php -r "if(strpos(@exec('composer -V'), 'Composer version') === false) {throw new Exception('Composer not found');}"
      - name: Testing Extensions
        run: |
          php -m
          php -r "if(! extension_loaded('mbstring')) {throw new Exception('mbstring not found');}"
          php -r "if(! extension_loaded('pcov')) {throw new Exception('PCOV not found');}"
      - name: Testing ini values
        run: |
          php -r "if(ini_get('post_max_size')!='256M') {throw new Exception('post_max_size not added');}"
          php -r "if(ini_get('short_open_tag')!=1) {throw new Exception('short_open_tag not added');}"
          php -r "if(ini_get('date.timezone')!='Asia/Kolkata') {throw new Exception('date.timezone not added');}"
      - name: Test JIT
        run: |
          php -r "if(! extension_loaded('Zend OPcache')) {throw new Exception('Zend OPcache not found');}"
          php -r "if(ini_get('opcache.jit_buffer_size')!='256M') {throw new Exception('opcache.jit_buffer_size not set');}"
          php -r "if(ini_get('opcache.jit')!=1235) {throw new Exception('opcache.jit not set');}"
          php -r "if(ini_get('pcre.jit')!=1) {throw new Exception('pcre.jit not set');}"
      - name: Benchmark JIT
        run: |
          curl -o bench.php https://raw.githubusercontent.com/php/php-src/master/Zend/bench.php
          php bench.php